import { Geist, Geist_Mono } from "next/font/google";
import  "./globals.css";
import localFont from 'next/font/local'

const causten = localFont({
  src: [

    {
      path: '../../public/fonts/Causten-Round/Causten-Bold.otf',
      style: 'normal',
    },
  ],
  variable: '--font-causten',
})
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});



const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body
        className={`${causten.variable} ${causten.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
